### ISSUE TITLE
The Dataset

### ISSUE THREAD

**Issue by zs963048949** [ashnilkumar/colearn#2]
Hi Ashnil,
Your work is excellent.I really have a urgent demand in multi-modality medical dataset.Could you share your Pet-Ct dataset?Thanks in advace.
best.

**Comment by ashnilkumar** [comment]
Hi, unfortunately the dataset is a private one and cannot be shared. I suggest looking at [TCIA](https://www.cancerimagingarchive.net/) for PET-CT data. They have a number of such sets available there.
